// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarBrain.Api.Data;

#nullable disable

namespace SolarBrain.Api.Migrations
{
    [DbContext(typeof(SolarBrainDbContext))]
    [Migration("20260417192514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SolarBrain.Api.Models.Entities.Battery", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AvailableSa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double>("CapacityKwh")
                        .HasColumnType("REAL");

                    b.Property<string>("Chemistry")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("CycleLife")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DodPct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GridScenario")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxChargeKw")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxDischargeKw")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double>("PriceSar")
                        .HasColumnType("REAL");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VoltageV")
                        .HasColumnType("REAL");

                    b.Property<int>("WarrantyYears")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Batteries");
                });

            modelBuilder.Entity("SolarBrain.Api.Models.Entities.DeratingFactors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AnnualDegradation")
                        .HasColumnType("REAL");

                    b.Property<double>("PerformanceRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("SoilingFactor")
                        .HasColumnType("REAL");

                    b.Property<double>("SystemLosses")
                        .HasColumnType("REAL");

                    b.Property<double>("TempDerating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DeratingFactors");
                });

            modelBuilder.Entity("SolarBrain.Api.Models.Entities.Inverter", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AvailableSa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double>("CapacityKw")
                        .HasColumnType("REAL");

                    b.Property<double>("EfficiencyPct")
                        .HasColumnType("REAL");

                    b.Property<string>("GridScenario")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxPvInputKw")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double>("PriceSar")
                        .HasColumnType("REAL");

                    b.Property<bool>("SecApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyYears")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Inverters");
                });

            modelBuilder.Entity("SolarBrain.Api.Models.Entities.Panel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("AreaM2")
                        .HasColumnType("REAL");

                    b.Property<bool>("AvailableSa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double>("EfficiencyPct")
                        .HasColumnType("REAL");

                    b.Property<string>("GridScenario")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerWp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PriceSar")
                        .HasColumnType("REAL");

                    b.Property<bool>("SecApproved")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TempCoefficientPct")
                        .HasColumnType("REAL");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyYears")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Panels");
                });

            modelBuilder.Entity("SolarBrain.Api.Models.Entities.ProtectionItem", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceBasis")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("PriceSar")
                        .HasColumnType("REAL");

                    b.HasKey("Key");

                    b.ToTable("ProtectionItems");
                });

            modelBuilder.Entity("SolarBrain.Api.Models.Entities.Region", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CitiesCsv")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<double>("GhiKwhM2Day")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("SolarBrain.Api.Models.Entities.SizingConstants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AutonomyHoursOffGrid")
                        .HasColumnType("REAL");

                    b.Property<double>("AutonomyHoursOnGrid")
                        .HasColumnType("REAL");

                    b.Property<double>("DieselConsumptionLphPerKva")
                        .HasColumnType("REAL");

                    b.Property<double>("DieselPriceSarPerLiter")
                        .HasColumnType("REAL");

                    b.Property<double>("GeneratorPowerFactor")
                        .HasColumnType("REAL");

                    b.Property<double>("InverterOversizeFactor")
                        .HasColumnType("REAL");

                    b.Property<double>("PeakLoadFactor")
                        .HasColumnType("REAL");

                    b.Property<double>("SafetyFactorOffGrid")
                        .HasColumnType("REAL");

                    b.Property<double>("SafetyFactorOnGrid")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SizingConstants");
                });

            modelBuilder.Entity("SolarBrain.Api.Models.Entities.Tariff", b =>
                {
                    b.Property<string>("UserType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("ExportRateSarKwh")
                        .HasColumnType("REAL");

                    b.Property<double>("OffpeakRateSarKwh")
                        .HasColumnType("REAL");

                    b.Property<double>("PeakRateSarKwh")
                        .HasColumnType("REAL");

                    b.Property<double>("RateSarKwh")
                        .HasColumnType("REAL");

                    b.HasKey("UserType");

                    b.ToTable("Tariffs");
                });
#pragma warning restore 612, 618
        }
    }
}
